version: '3'

services:
  database:
    image: arm64v8/postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: "docker"
    ports:
      - 5432:5432
    volumes: 
      - ./postgres-data:/var/lib/postgresql/data