version: '3'

services:
  database:
    image: arm64v8/postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: "docker"
    ports:
      - 5432:5432
    volumes:
      - ./postgres-data:/var/lib/postgresql/data

  mongodb:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    volumes:
      - ./mongo-data:/data/db

  redisbarber:
    image: redis:alpine
    restart: always
    ports:
      - 6379:6379
